---
# maintains ports, bianry or repo urls

org: encapsulate

default_node_types:
  - validator
  - default

tmp_dir: /tmp

go:
  root: /usr/local/go
  path: "{{ tmp_dir }}/go"
  module111: "on"

omniflix:
  validator:
    source_url: https://github.com/OmniFlix/omniflixhub
    ports:
      prefix: 100
      suffix:
        # Used for both p2p_laddr and p2p_external_address
        p2p: 56
        rpc: 57
        abci: 58
        prometheus: 60
        pprof: 61
        rest_api: 17
        rosetta: 80
        grpc: 90
        grpc_web: 91
  fullnode:
    source_url: https://github.com/OmniFlix/omniflixhub
    ports:
      prefix: 100
      suffix:
        # Used for both p2p_laddr and p2p_external_address
        p2p: 56
        rpc: 57
        abci: 58
        prometheus: 60
        pprof: 61
        rest_api: 17
        rosetta: 80
        grpc: 90
        grpc_web: 91


# todo: init and and update, rpc setting in config

