---
# maintains versions and can overwrite all.yml
celestia:
  chain_id: celestia
  validator:
    version: v4.0.10
    go:
      version: 1.24.1
  fullnode:
    version: v4.0.10
    go:
      version: 1.24.1
  snapshot_url: https://snapshots.polkachu.com/snapshots/celestia/celestia_4098687.tar.lz4

umee:
  chain_id: umee-1
  validator:
    version: v6.7.3
    go:
      version: 1.23.1
    wasmvm:
      version: v1.5.5
  pf:
    version: umee/v2.4.4
    keyring_dir: "/opt/umee"
    go:
      version: 1.23.1
    wasmvm:
      version: v1.5.5
  snapshot_url: https://snapshots.polkachu.com/snapshots/umee/umee_15888336.tar.lz4

agoric:
  chain_id: agoric-3
  validator:
    version: agoric-upgrade-21
    go:
      version: 1.23.1
    node:
      version: v20.19.3
  snapshot_url: https://snapshots.kjnodes.com/agoric/snapshot_latest.tar.lz4

axelar:
  chain_id: axelar-dojo-1
  validator:
    version: v1.2.1
    wasmvm:
      version: v1.5.8
  broadcaster_address: axelar17x2hs7tta7nkmh788f2d9q60nt8mnk370t5ncs
  vald:
    version: v1.2.1
    node_address: "tcp://validator.axelar.mainnet.encapsulate.xyz:11457"
    validator_address: axelarvaloper1s0lankh33kprer2l22nank5rvsuh9ksa6utflp
    wasmvm:
      version: v1.5.8
    vote_metrics_url: https://api.axelarscan.io/validator/searchPolls
    heartbeat_metrics_url: https://api.axelarscan.io/validator/searchHeartbeats
    tofnd_host: tofnd.axelar.mainnet.encapsulate.xyz
  tofnd:
    version: v0.10.1
  snapshot_url: https://snapshots.polkachu.com/snapshots/axelar/axelar_16464939.tar.lz4

quicksilver:
  chain_id: quicksilver-2
  validator:
    version: v1.8.1
    go:
      version: 1.23.7
  snapshot_url: https://server-2.itrocket.net/mainnet/quicksilver/quicksilver_2025-01-26_11113196_snap.tar.lz4

juno:
  chain_id: juno-1
  validator:
    version: v29.0.0
    go:
      version: 1.23.4
    wasmvm:
      version: v2.2.4
  fullnode:
    version: v29.0.0
    go:
      version: 1.23.4
    wasmvm:
      version: v2.2.4
  snapshot_url: https://snapshots.polkachu.com/snapshots/juno/juno_23405873.tar.lz4

stargaze:
  chain_id: stargaze-1
  validator:
    version: v17.0.0
    go:
      version: 1.24.1
    wasmvm:
      version: v2.2.4
  snapshot_url: https://snapshots.polkachu.com/snapshots/stargaze/stargaze_17346976.tar.lz4

althea:
  chain_id: althea_258432-1
  validator:
    version: v1.5.1
    go:
      version: 1.23.5
  snapshot_url: https://snapshots.polkachu.com/snapshots/althea/althea_4526012.tar.lz4

mantle:
  chain_id: mantle-1
  validator:
    version: v1.0.1
    go:
      version: 1.23.5
  snapshot_url: https://snapshots.polkachu.com/snapshots/assetmantle/assetmantle_15464734.tar.lz4

c4e:
  chain_id: perun-1
  validator:
    version: v1.4.3
    go:
      version: 1.23.5
    wasmvm:
      version: v1.5.2
  snapshot_url: https://snapshots-1.stake-town.com/c4e/perun-1_latest.tar.lz4

gitopia:
  chain_id: gitopia
  validator:
    version: v6.0.0
    go:
      version: 1.23.5
  snapshot_url: https://snapshots.polkachu.com/snapshots/gitopia/gitopia_33698742.tar.lz4

humans:
  chain_id: humans_1089-1
  validator:
    version: master
    go:
      version: 1.23.5
  snapshot_url: https://snapshots.polkachu.com/snapshots/humans/humans_9428312.tar.lz4

omniflix:
  chain_id: omniflixhub-1
  validator:
    version: v6.0.0
    go:
      version: 1.23.9
    wasmvm:
      version: v2.1.6
  snapshot_url: https://snapshots.polkachu.com/snapshots/omniflix/omniflix_16286631.tar.lz4

gravity:
  chain_id: gravity-bridge-3
  validator:
    version: v1.13.3
  snapshot_url: https://snapshots.polkachu.com/snapshots/gravity/gravity_15740467.tar.lz4
  orchestrator:
    version: v1.13.3
  node_grpc_address: http://localhost:13090
  public_api_address: https://gravity-api.polkachu.com
  address: gravity1v78rxsl5ycptaq2dq5mu6ftzqcgk2aqtp2ghsp

sommelier:
  chain_id: sommelier-3
  validator:
    version: v9.3.0
    go:
      version: 1.23.5
  snapshot_url: https://snapshots.polkachu.com/snapshots/sommelier/sommelier_18741706.tar.lz4
  orchestrator:
    version: v4.2.7
  steward:
    version: v4.2.7
  node_grpc_address: http://localhost:13290
  public_grpc_address: sommelier-grpc.polkachu.com:14190
  address: somm1v78rxsl5ycptaq2dq5mu6ftzqcgk2aqtfx4ryr

ixo:
  chain_id: ixo-5
  validator:
    version: v5.0.0
    go:
      version: 1.23.5
    wasmvm:
      version: v1.5.4
  snapshot_url: https://server-1.stavr.tech/Mainnet/Ixo/ixo-snap-2.tar.lz4

paloma:
  chain_id: tumbler
  validator:
    version: v2.4.15
    go:
      version: 1.24.4
    wasmvm:
      version: v2.1.3
  snapshot_url: https://snapshots.polkachu.com/snapshots/paloma/paloma_32327947.tar.lz4
  pigeon:
    version: v2.3.5
    keyring_dir: "/opt/paloma"
    rpc_url: http://localhost:13657

planq:
  chain_id: planq_7070-2
  validator:
    version: v2.1.2
    go:
      version: 1.23.5
  snapshot_url: https://snapshots.polkachu.com/snapshots/planq/planq_13286525.tar.lz4

pylon:
  chain_id: pylons-mainnet-1
  validator:
    version: v1.1.4
    go:
      version: 1.23.5
  snapshot_url: https://config.noders.services/pylons/data.tar.lz4

qwoyn:
  chain_id: qwoyn-1
  validator:
    version: v5.4.1
    go:
      version: 1.23.5
    wasmvm:
      version: v1.2.6
  snapshot_url: https://server-1.stavr.tech/Mainnet/Qwoyn/qwoyn-snap-2.tar.lz4

terra:
  chain_id: phoenix-1
  validator:
    version: v2.17.3
    go:
      version: 1.23.5
    wasmvm:
      version: v2.2.4
  fullnode:
    version: v2.17.3
    go:
      version: 1.23.5
    wasmvm:
      version: v2.2.4
  snapshot_url: https://snapshots.polkachu.com/snapshots/terra/terra_14374222.tar.lz4

passage:
  chain_id: passage-2
  validator:
    version: v2.6.0
    go:
      version: 1.23.5
    wasmvm:
      version: v1.5.7
  snapshot_url: https://snapshots.polkachu.com/snapshots/passage/passage_12539367.tar.lz4

tenet:
  chain_id: tenet_1559-1
  validator:
    version: 11.2.1
  snapshot_url: https://support.synergynodes.com/snapshots/tenet_mainnet/tenet_16535716.tar.lz4

lumera:
  chain_id: lumera-mainnet-1
  validator:
    version: v1.6.1
    wasmvm:
      version: v2.1.2
  snapshot_url: https://snapshots.polkachu.com/snapshots/lumera/lumera_863081.tar.lz4
  supernode:
    version: v2.0.0-alpha
    identity:
    grpc_addr: localhost:15090
