---
# maintains versions and can overwrite all.yml
omniflix:
  chain_id: flixnet-4
  validator:
    version: v6.0.0-alpha.2
    go:
      version: 1.23.9
    wasmvm:
      version: v2.1.6
  snapshot_url: http://quicksync.cros-nest.com/transfer/flixnet-4-14267555.tar

quicksilver:
  chain_id: rhye-3
  validator:
    version: v1.9.3
    go:
      version: 1.24.5
    valoper_address: quickvaloper1uj98474n68v52ycwu25chs6ldj77svrtzgq48h
    api_urls:
      - "https://quicksilver-testnet-api.itrocket.net"
      - "https://quicksilver-testnet-api.polkachu.com"
      - "https://quick.api.t.stavr.tech"
  snapshot_url: https://server-4.itrocket.net/testnet/quicksilver/quicksilver_2024-11-23_686128_snap.tar.lz4

celestia:
  chain_id: mocha-4
  validator:
    version: v4.0.10-mocha
    go:
      version: 1.24.1
  snapshot_url: https://snapshots.polkachu.com/testnet-snapshots/celestia/celestia_3269266.tar.lz4

humans:
  chain_id: humans_3000-31
  validator:
    version: master
    go:
      version: 1.21.6
    valoper_address: humanvaloper1l9wxdywayz6c7a93frfdxnn6uw6e6p33z4gxn7
    api_urls:
      - "https://humans-testnet.api.kjnodes.com"
  snapshot_url: https://server-4.itrocket.net/testnet/humans/humans_2024-11-23_8405437_snap.tar.lz4

ojo:
  chain_id: ojo-devnet
  validator:
    version: v0.1.2
    go:
      version: 1.21.6
  snapshot_url: https://snapshots.polkachu.com/testnet-snapshots/ojo/ojo_9738727.tar.lz4

umee:
  chain_id: canon-4
  validator:
    version: v6.7.4-rc1
    go:
      version: 1.23.1
    wasmvm:
      version: v1.5.5
  pf:
    version: umee/v2.4.4
    keyring_dir: "/opt/umee"
    go:
      version: 1.23.1
    wasmvm:
      version: v1.5.9
  snapshot_url: https://snapshots-testnet.stake-town.com/umee/canon-4_latest.tar.lz4

c4e:
  chain_id: babajaga-1
  validator:
    version: v1.4.0
    go:
      version: 1.19.1
    wasmvm:
      version: v1.5.2
    valoper_address: c4evaloper1vaxz9hyn8sq5vk3jgdhkge8xefuhz6xt5qnmpy
    api_urls:
      - "https://lcd-testnet.c4e.io"
      - "https://c4e.api.t.stavr.tech"
  snapshot_url: https://snapshots-testnet.stake-town.com/c4e/babajaga-1_latest.tar.lz4
  rpc_url: https://c4e-testnet-rpc.stake-town.com:443

axelar:
  chain_id: axelar-testnet-lisbon-3
  validator:
    version: v1.3.11
    wasmvm:
      version: v2.2.4
    valoper_address: axelarvaloper1klj7fs4d63krf2vpcts3wc5csadl9tdsfuz9mh
    api_urls:
      - "https://axelar-testnet-api.polkachu.com"
      - "https://axelar-rest-1.staketab.org"
      - "https://axelar-testnet-lcd.qubelabs.io"
  fullnode:
    version: v1.3.11
    wasmvm:
      version: v2.2.4
  vald:
    version: v1.3.11
    node_address: "tcp://localhost:11457"
    wasmvm:
      version: v2.2.4
    vote_metrics_url: https://testnet.api.axelarscan.io/validator/searchPolls
    tofnd_host: localhost
  tofnd:
    version: v1.0.1
  snapshot_url: https://snapshots.polkachu.com/testnet-snapshots/axelar/axelar_16356359.tar.lz4

agoric:
  chain_id: agoric-emerynet-9
  validator:
    version: agoric-upgrade-22-rc1
    go:
      version: 1.23.1
    node:
      version: v20.19.3
    valoper_address: agoricvaloper1kg5dkr8z785rr7u0mxdhrjj0dh86qekaj4jj0u
    api_urls:
      - "https://agoric-testnet-api.polkachu.com"
      - "https://emerynet.api.agoric.net"
  snapshot_url: https://snapshots.polkachu.com/testnet-snapshots/agoric/agoric_879650.tar.lz4
  rpc_url: https://agoric-testnet-rpc.polkachu.com:443

pell:
  chain_id: ignite_186-1
  validator:
    version: v1.4.2
    wasmvm:
      version: v2.1.2
  snapshot_url: https://ss-t.pell.nodestake.org/2024-12-23_pell_241564.tar.lz4

lumera:
  chain_id: lumera-testnet-2
  validator:
    version: v1.11.1-hotfix
    wasmvm:
      version: v3.0.2
    valoper_address: lumeravaloper1uj98474n68v52ycwu25chs6ldj77svrtqyddca
    api_urls:
      - "https://lumera-testnet-api.polkachu.com"
      - "https://lcd.testnet.lumera.io"
  snapshot_url: https://snapshots.polkachu.com/testnet-snapshots/lumera/lumera_712731.tar.lz4
  supernode:
    version: v2.4.5-testnet
    identity: lumera1wmq0wu60a63cnx5fhln0m0zv6u5rq6dw0dhvhn
    keyfile_name: 76c0f7734feea3899a89bfe6fdbc4cd7283069ae.address
    grpc_addr: localhost:15090

terra:
  chain_id: pisco-1
  validator:
    version: v2.19.0
    go:
      version: 1.23.5
    wasmvm:
      version: v2.2.4
    valoper_address: terravaloper19zp8zstmwn5mfak2hkydexrl0xddt4dyqj42cx
    api_urls:
      - "https://terra-testnet-api.polkachu.com"
  snapshot_url: https://snapshots.polkachu.com/testnet-snapshots/terra/terra_18175931.tar.lz4
