---
# maintains versions and can overwrite all.yml
omniflix:
  validator:
    version: v0.12.0-alpha.1
    go:
      version: 1.21.6
  fullnode:
    version: v0.12.0-alpha.1
    go:
      version: 1.21.6

quicksilver:
  validator:
    version: v1.6.4
    go:
      version: 1.21.6
  fullnode:
    version: v1.6.4
    go:
      version: 1.21.6

celestia:
  validator:
    version: v2.3.1
    go:
      version: 1.23.1
  fullnode:
    version: v2.3.1
    go:
      version: 1.23.1

humans:
  validator:
    version: master
    go:
      version: 1.21.6
  fullnode:
    version: master
    go:
      version: 1.21.6

ojo:
  validator:
    version: v0.1.2
    go:
      version: 1.21.6
  fullnode:
    version: v0.1.2
    go:
      version: 1.21.6
