---
- name: Set up cosmos node
  hosts: all
  become: true
  gather_facts: true
  vars:
    allowed_node_types: [validator, fullnode]
  vars_files:
    - group_vars/all.
    - group_vars/ports.yml
    - group_vars/vault.yml
    - group_vars/{{ env }}.yml

  pre_tasks:
    - name: Setup environment and dependencies
      when: type in allowed_node_types
      block:
        - name: Include environment setup tasks
          ansible.builtin.include_tasks: tasks/setup_environment.yml
        - name: Include dependencies setup tasks
          ansible.builtin.include_tasks: tasks/setup_dependencies.yml

  tasks:
    - name: Run node playbook
      when: type in allowed_node_types
      block:
        - name: Include common handlers
          ansible.builtin.include_role:
            name: common
        - name: Include node role
          ansible.builtin.include_role:
            name: node
