---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    quicksilver:
      hosts:
        old.validator.quicksilver.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.quicksilver.mainnet.encapsulate.xyz:
          type: validator
    agoric:
      hosts:
        old.validator.agoric.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.agoric.mainnet.encapsulate.xyz:
          type: validator
    umee:
      hosts:
        old.validator.umee.mainnet.encapsulate.xyz:
          type: validator
        old.pf.umee.mainnet.encapsulate.xyz:
          type: pf
          pf_address: "umee1fk8xy9xy4lkuqjdsj380capumn30wlsmsuu8pm"
          validator_address: "umeevaloper1s0lankh33kprer2l22nank5rvsuh9ksavp35nh"
        ts.validator.umee.mainnet.encapsulate.xyz:
          type: validator
        ts.pf.umee.mainnet.encapsulate.xyz:
          type: pf
          pf_address: "umee1td75rn99evak5tmklqpl47vg5xzm5jea86z2n3"
          validator_address: "umeevaloper1p8uxq4ska2psv2k8wknljh568k5qfnwtcale5a"
    axelar:
      hosts:
        old.validator.axelar.mainnet.encapsulate.xyz:
          type: validator
          support_amplifier: true
        old.vald.axelar.mainnet.encapsulate.xyz:
          type: vald
          broadcaster_address: axelar17x2hs7tta7nkmh788f2d9q60nt8mnk370t5ncs
          validator_address: axelarvaloper1s0lankh33kprer2l22nank5rvsuh9ksa6utflp
        old.tofnd.axelar.mainnet.encapsulate.xyz:
          type: tofnd
        ts.validator.axelar.mainnet.encapsulate.xyz:
          type: validator
          support_amplifier: true
        ts.vald.axelar.mainnet.encapsulate.xyz:
          type: vald
          broadcaster_address: axelar1td75rn99evak5tmklqpl47vg5xzm5jea3zfauz
          validator_address: axelarvaloper1p8uxq4ska2psv2k8wknljh568k5qfnwtwq9yct
        ts.tofnd.axelar.mainnet.encapsulate.xyz:
          type: tofnd
    stargaze:
      hosts:
        old.validator.stargaze.mainnet.encapsulate.xyz:
          type: validator
    althea:
      hosts:
        old.validator.althea.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
        ts.validator.althea.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
    mantle:
      hosts:
        old.validator.mantle.mainnet.encapsulate.xyz:
          type: validator
    c4e:
      hosts:
        ts.validator.c4e.mainnet.encapsulate.xyz:
          type: validator
    gitopia:
      hosts:
        old.validator.gitopia.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.gitopia.mainnet.encapsulate.xyz:
          type: validator
        ts.fullnode.gitopia.mainnet.encapsulate.xyz:
          type: fullnode
    humans:
      hosts:
        old.validator.humans.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
        ts.validator.humans.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
    gravity:
      hosts:
        old.validator.gravity.mainnet.encapsulate.xyz:
          type: validator
        old.orchestrator.gravity.mainnet.encapsulate.xyz:
          type: orchestrator
          orchestrator_address: "gravity1v78rxsl5ycptaq2dq5mu6ftzqcgk2aqtp2ghsp"
        ts.validator.gravity.mainnet.encapsulate.xyz:
          type: validator
        ts.orchestrator.gravity.mainnet.encapsulate.xyz:
          type: orchestrator
          orchestrator_address: "gravity1y5ahycftx9gty47p45cp9kjksnmgxk284zr79p"
    sommelier:
      hosts:
        old.validator.sommelier.mainnet.encapsulate.xyz:
          type: validator
        old.orchestrator.sommelier.mainnet.encapsulate.xyz:
          type: orchestrator
          orchestrator_address: "sommelier1v78rxsl5ycptaq2dq5mu6ftzqcgk2aqtp2ghsp"
        old.steward.sommelier.mainnet.encapsulate.xyz:
          type: steward
        ts.validator.sommelier.mainnet.encapsulate.xyz:
          type: validator
        ts.orchestrator.sommelier.mainnet.encapsulate.xyz:
          type: orchestrator
          orchestrator_address: ""
        ts.steward.sommelier.mainnet.encapsulate.xyz:
          type: steward
    ixo:
      hosts:
        old.validator.ixo.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.ixo.mainnet.encapsulate.xyz:
          type: validator
    planq:
      hosts:
        old.validator.planq.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
    qwoyn:
      hosts:
        old.validator.qwoyn.mainnet.encapsulate.xyz:
          type: validator
    terra:
      hosts:
        ts.validator.terra.mainnet.encapsulate.xyz:
          type: validator
        ts.fullnode.terra.mainnet.encapsulate.xyz:
          type: fullnode
    passage:
      hosts:
        old.validator.passage.mainnet.encapsulate.xyz:
          type: validator
    tenet:
      hosts:
        old.validator.tenet.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
    lumera:
      hosts:
        old.validator.lumera.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.lumera.mainnet.encapsulate.xyz:
          type: validator
        supernode.lumera.mainnet.encapsulate.xyz:
          type: supernode
        ts.fullnode.lumera.mainnet.encapsulate.xyz:
          type: fullnode
