---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    celestia:
      hosts:
        validator.celestia.mainnet.encapsulate.xyz:
          type: validator
        fullnode.celestia.mainnet.encapsulate.xyz:
          type: fullnode
    quicksilver:
      hosts:
        validator.quicksilver.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.quicksilver.mainnet.encapsulate.xyz:
          type: validator
    agoric:
      hosts:
        validator.agoric.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.agoric.mainnet.encapsulate.xyz:
          type: validator
    umee:
      hosts:
        validator.umee.mainnet.encapsulate.xyz:
          type: validator
        pf.umee.mainnet.encapsulate.xyz:
          type: pf
          pf_address: "umee1fk8xy9xy4lkuqjdsj380capumn30wlsmsuu8pm"
          validator_address: "umeevaloper1s0lankh33kprer2l22nank5rvsuh9ksavp35nh"
        ts.validator.umee.mainnet.encapsulate.xyz:
          type: validator
        ts.pf.umee.mainnet.encapsulate.xyz:
          type: pf
          pf_address: "umee1td75rn99evak5tmklqpl47vg5xzm5jea86z2n3"
          validator_address: "umeevaloper1p8uxq4ska2psv2k8wknljh568k5qfnwtcale5a"
    axelar:
      hosts:
        validator.axelar.mainnet.encapsulate.xyz:
          type: validator
          support_amplifier: true
        vald.axelar.mainnet.encapsulate.xyz:
          type: vald
          broadcaster_address: axelar17x2hs7tta7nkmh788f2d9q60nt8mnk370t5ncs
        tofnd.axelar.mainnet.encapsulate.xyz:
          type: tofnd
        ts.validator.axelar.mainnet.encapsulate.xyz:
          type: validator
          support_amplifier: true
        ts.vald.axelar.mainnet.encapsulate.xyz:
          type: vald
          broadcaster_address: axelar1td75rn99evak5tmklqpl47vg5xzm5jea3zfauz
        ts.tofnd.axelar.mainnet.encapsulate.xyz:
          type: tofnd
    juno:
      hosts:
        validator.juno.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.juno.mainnet.encapsulate.xyz:
          type: validator
        fullnode.juno.mainnet.encapsulate.xyz:
          type: fullnode
    stargaze:
      hosts:
        validator.stargaze.mainnet.encapsulate.xyz:
          type: validator
    althea:
      hosts:
        validator.althea.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
        ts.validator.althea.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
    mantle:
      hosts:
        validator.mantle.mainnet.encapsulate.xyz:
          type: validator
    c4e:
      hosts:
        validator.c4e.mainnet.encapsulate.xyz:
          type: validator
    gitopia:
      hosts:
        validator.gitopia.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.gitopia.mainnet.encapsulate.xyz:
          type: validator
        fullnode.gitopia.mainnet.encapsulate.xyz:
          type: fullnode
    humans:
      hosts:
        validator.humans.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
        ts.validator.humans.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
    omniflix:
      hosts:
        validator.omniflix.mainnet.encapsulate.xyz:
          type: validator
    gravity:
      hosts:
        validator.gravity.mainnet.encapsulate.xyz:
          type: validator
        orchestrator.gravity.mainnet.encapsulate.xyz:
          type: orchestrator
          orchestrator_address: "gravity1v78rxsl5ycptaq2dq5mu6ftzqcgk2aqtp2ghsp"
        ts.validator.gravity.mainnet.encapsulate.xyz:
          type: validator
        ts.orchestrator.gravity.mainnet.encapsulate.xyz:
          type: orchestrator
          orchestrator_address: "gravity1y5ahycftx9gty47p45cp9kjksnmgxk284zr79p"
    sommelier:
      hosts:
        validator.sommelier.mainnet.encapsulate.xyz:
          type: validator
        orchestrator.sommelier.mainnet.encapsulate.xyz:
          type: orchestrator
          orchestrator_address: "sommelier1v78rxsl5ycptaq2dq5mu6ftzqcgk2aqtp2ghsp"
        steward.sommelier.mainnet.encapsulate.xyz:
          type: steward
        ts.validator.sommelier.mainnet.encapsulate.xyz:
          type: validator
        ts.orchestrator.sommelier.mainnet.encapsulate.xyz:
          type: orchestrator
          orchestrator_address: ""
        ts.steward.sommelier.mainnet.encapsulate.xyz:
          type: steward
    ixo:
      hosts:
        validator.ixo.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.ixo.mainnet.encapsulate.xyz:
          type: validator
    paloma:
      hosts:
        validator.paloma.mainnet.encapsulate.xyz:
          type: validator
        pigeon.paloma.mainnet.encapsulate.xyz:
          type: pigeon
    planq:
      hosts:
        validator.planq.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
    pylon:
      hosts:
        validator.pylon.mainnet.encapsulate.xyz:
          type: validator
    qwoyn:
      hosts:
        validator.qwoyn.mainnet.encapsulate.xyz:
          type: validator
    terra:
      hosts:
        validator.terra.mainnet.encapsulate.xyz:
          type: validator
        fullnode.terra.mainnet.encapsulate.xyz:
          type: fullnode
    passage:
      hosts:
        validator.passage.mainnet.encapsulate.xyz:
          type: validator
    tenet:
      hosts:
        validator.tenet.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
    lumera:
      hosts:
        validator.lumera.mainnet.encapsulate.xyz:
          type: validator
        supernode.lumera.mainnet.encapsulate.xyz:
          type: supernode
        fullnode.lumera.mainnet.encapsulate.xyz:
          type: fullnode
