---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    agoric:
      hosts:
        old.validator.agoric.mainnet.encapsulate.xyz:
          type: validator
        ts.validator.agoric.mainnet.encapsulate.xyz:
          type: validator
    axelar:
      hosts:
        old.validator.axelar.mainnet.encapsulate.xyz:
          type: validator
          support_amplifier: true
        old.vald.axelar.mainnet.encapsulate.xyz:
          type: vald
          broadcaster_address: axelar17x2hs7tta7nkmh788f2d9q60nt8mnk370t5ncs
          validator_address: axelarvaloper1s0lankh33kprer2l22nank5rvsuh9ksa6utflp
        old.tofnd.axelar.mainnet.encapsulate.xyz:
          type: tofnd
        ts.validator.axelar.mainnet.encapsulate.xyz:
          type: validator
          support_amplifier: true
        ts.vald.axelar.mainnet.encapsulate.xyz:
          type: vald
          broadcaster_address: axelar1td75rn99evak5tmklqpl47vg5xzm5jea3zfauz
          validator_address: axelarvaloper1p8uxq4ska2psv2k8wknljh568k5qfnwtwq9yct
        ts.tofnd.axelar.mainnet.encapsulate.xyz:
          type: tofnd
    althea:
      hosts:
        ts.validator.althea.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
    c4e:
      hosts:
        ts.validator.c4e.mainnet.encapsulate.xyz:
          type: validator
    gitopia:
      hosts:
        ts.validator.gitopia.mainnet.encapsulate.xyz:
          type: validator
        ts.fullnode.gitopia.mainnet.encapsulate.xyz:
          type: fullnode
    humans:
      hosts:
        ts.validator.humans.mainnet.encapsulate.xyz:
          type: validator
          execution_client: true
    gravity:
      hosts:
        ts.validator.gravity.mainnet.encapsulate.xyz:
          type: validator
        ts.orchestrator.gravity.mainnet.encapsulate.xyz:
          type: orchestrator
          orchestrator_address: "gravity1v78rxsl5ycptaq2dq5mu6ftzqcgk2aqtp2ghsp"
    sommelier:
      hosts:
        ts.validator.sommelier.mainnet.encapsulate.xyz:
          type: validator
        ts.orchestrator.sommelier.mainnet.encapsulate.xyz:
          type: orchestrator
          orchestrator_address: "sommelier1v78rxsl5ycptaq2dq5mu6ftzqcgk2aqtp2ghsp"
        ts.steward.sommelier.mainnet.encapsulate.xyz:
          type: steward
    ixo:
      hosts:
        ts.validator.ixo.mainnet.encapsulate.xyz:
          type: validator
    terra:
      hosts:
        ts.validator.terra.mainnet.encapsulate.xyz:
          type: validator
        ts.fullnode.terra.mainnet.encapsulate.xyz:
          type: fullnode
    passage:
      hosts:
        old.validator.passage.mainnet.encapsulate.xyz:
          type: validator
    lumera:
      hosts:
        ts.validator.lumera.mainnet.encapsulate.xyz:
          type: validator
        supernode.lumera.mainnet.encapsulate.xyz:
          type: supernode
        ts.fullnode.lumera.mainnet.encapsulate.xyz:
          type: fullnode
    paloma:
      hosts:
        ts.validator.paloma.mainnet.encapsulate.xyz:
          type: validator
        ts.pigeon.paloma.mainnet.encapsulate.xyz:
          type: pigeon
