---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    quicksilver:
      hosts:
        ts.validator.quicksilver.testnet.encapsulate.xyz:
          type: validator
    humans:
      hosts:
        ts.validator.humans.testnet.encapsulate.xyz:
          type: validator
          execution_client: true
    c4e:
      hosts:
        ts.validator.c4e.testnet.encapsulate.xyz:
          type: validator
    axelar:
      hosts:
        ts.validator.axelar.testnet.encapsulate.xyz:
          type: validator
          support_amplifier: true
        ts.fullnode.axelar.testnet.encapsulate.xyz:
          type: fullnode
        ts.vald.axelar.testnet.encapsulate.xyz:
          type: vald
          broadcaster_address: axelar1fqw4e8080u9wlv5fup38qvquf2605gvv58fwyd
          validator_address: axelarvaloper1klj7fs4d63krf2vpcts3wc5csadl9tdsfuz9mh
        ts.tofnd.axelar.testnet.encapsulate.xyz:
          type: tofnd
    agoric:
      hosts:
        ts.validator.agoric.testnet.encapsulate.xyz:
          type: validator
    lumera:
      hosts:
        ts.validator.lumera.testnet.encapsulate.xyz:
          type: validator
        ts.supernode.lumera.testnet.encapsulate.xyz:
          type: supernode
    terra:
      hosts:
        ts.validator.terra.testnet.encapsulate.xyz:
          type: validator
