---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    omniflix:
      hosts:
        validator.omniflix.testnet.encapsulate.xyz:
          type: validator
    quicksilver:
      hosts:
        validator.quicksilver.testnet.encapsulate.xyz:
          type: validator
    celestia:
      hosts:
        validator.celestia.testnet.encapsulate.xyz:
          type: validator
    humans:
      hosts:
        validator.humans.testnet.encapsulate.xyz:
          type: validator
          execution_client: true
    ojo:
      hosts:
        validator.ojo.testnet.encapsulate.xyz:
          type: validator
    umee:
      hosts:
        validator.umee.testnet.encapsulate.xyz:
          type: validator
        pf.umee.testnet.encapsulate.xyz:
          type: pf
    c4e:
      hosts:
        validator.c4e.testnet.encapsulate.xyz:
          type: validator
    axelar:
      hosts:
        validator.axelar.testnet.encapsulate.xyz:
          type: validator
          support_amplifier: true
        fullnode.axelar.testnet.encapsulate.xyz:
          type: fullnode
        axelar_vald_host:
          ansible_host: validator.axelar.testnet.encapsulate.xyz
          type: vald
          vald_axelar_home: /opt/axelar
        axelar_tofnd_host:
          ansible_host: validator.axelar.testnet.encapsulate.xyz
          type: tofnd
    agoric:
      hosts:
        validator.agoric.testnet.encapsulate.xyz:
          type: validator
    pell:
      hosts:
        validator.pell.testnet.encapsulate.xyz:
          type: validator
          execution_client: true
