---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    axelar:
      hosts:
        fullnode.axelar.testnet.encapsulate.xyz:
          type: fullnode
        validator.axelar.testnet.encapsulate.xyz:
          type: validator
          support_amplifier: tue
