---
- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  loop:
    - make
    - build-essential
    - gcc
    - git
    - jq
    - chrony
    - lz4
    - yq # failed: [5.78.92.20] (item=yq) => {"ansible_loop_var": "item", "changed": false, "item": "yq", "msg": "No package matching 'yq' is available"}

- name: Remove existing Go directories (if any)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ go.root }}"
    - "{{ go.path }}"
