---
- name: Install apt packages
  ansible.builtin.apt:
    name:
      - make
      - build-essential
      - gcc
      - git
      - jq
      - chrony
      - lz4
      - yq
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Remove existing Go directories (if any)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ go.root }}"
    - "{{ go.path }}"
  when: vars[project][type].go.version is defined
