---
# maintains directories and paths
node_home_dir: /opt/{{ service_identifier }}

node_bin_dir: "{{ node_home_dir }}/bin"
node_config_dir: "{{ node_home_dir }}/config"
node_data_dir: "{{ node_home_dir }}/data"
node_env_dir: "{{ node_home_dir }}/environment"
node_lib_dir: "{{ node_home_dir }}/lib"
node_log_dir: "{{ node_home_dir }}/log"

node_directories:
  - "{{ node_home_dir }}"
  - "{{ node_bin_dir }}"
  - "{{ node_config_dir }}"
  - "{{ node_env_dir }}"
  - "{{ node_data_dir }}"
  - "{{ node_lib_dir }}"
  - "{{ node_log_dir }}"

node_config_file_path: "{{ node_config_dir }}/{{ node_config_file_name }}"
node_app_file_path: "{{ node_config_dir }}/{{ node_app_file_name }}"
node_log_file_path: "{{ node_log_dir }}/{{ service_identifier }}.log"

node_environment_wasmvm_file_path: "{{ node_env_dir }}/{{ node_environment_wasmvm_file_name }}"
node_wasmvm_lib_file_path: "{{ node_lib_dir }}/{{ node_wasmvm_lib_file_name }}"

node_priv_validator_key_path: "{{ node_config_dir }}/{{ node_priv_validator_key_file_name }}"
node_node_key_path: "{{ node_config_dir }}/{{ node_node_key_file_name }}"
node_genesis_file_path: "{{ node_config_dir }}/{{ node_genesis_file_name }}"
node_priv_validator_state_file_path: "{{ node_data_dir }}/{{ node_priv_validator_state_file_name }}"
