---
- name: Pull the last line (pure JSON) and parse it
  ansible.builtin.set_fact:
    tx_json: "{{ (command_result.stdout.split('\n') | last) | from_json }}"

- name: Extract interesting fields
  ansible.builtin.set_fact:
    txhash: "{{ tx_json.txhash | default('Command didnt go through') }}"
    code: "{{ tx_json.code | default('Command didnt go through') }}"
    raw_log: "{{ tx_json.raw_log | default('Command didnt go through') }}"

- name: Show tx hash, code and raw-log
  ansible.builtin.debug:
    msg:
      Code: "{{ code }}"
      TX Hash: "{{ txhash }}"
      Raw Log: "{{ raw_log }}"
