---
- name: Display txhash, raw_log and codespace fields
  ansible.builtin.debug:
    msg: |
      TX Hash: {{ (command_result.stdout | regex_search('txhash: ([A-Fa-f0-9]+)', '\\1')) | default('N/A', true) }}
      Codespace: {{ (command_result.stdout | regex_search('codespace: "([^"]*)"', '\\1')) | default('N/A', true) }}
      Raw Log: {{ (command_result.stdout | regex_search("raw_log: '(.*?)'", '\\1')) | default('N/A', true) }}
