---
- name: Include the specific network's vars file
  ansible.builtin.include_vars:
    file: roles/node/defaults/main.yml

- name: Include the specific network's vars file
  ansible.builtin.include_vars:
    file: roles/node/vars/{{ env }}/{{ project }}.yml

- name: Stop service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: stopped

- name: Rollback cosmos-sdk and tendermint state by one height
  ansible.builtin.command: "{{ node_bin_dir }}/{{ service_identifier }} rollback --home {{ node_home_dir }}"
  register: rollback_result
  changed_when: false
  failed_when: rollback_result.rc != 0

- name: Set ownership for data directory
  ansible.builtin.file:
    path: "{{ node_data_dir }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    recurse: true

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: restarted
