---
- name: Perform unjail transaction and process results
  block:
    - name: Execute unjail transaction
      ansible.builtin.expect:
        command: >
          {{ node_bin_dir }}/{{ service_identifier }} tx slashing unjail --home {{ node_home_dir }}
          --from={{ key_name }}
          --fees {{ node_network_params.fee }}{{ node_network_params.denom }} --chain-id {{ vars[project].chain_id }} --yes
          --gas auto --gas-adjustment {{ node_network_params.gas_adjustment }}
          --node tcp://localhost:{{ rpc_port }}
          --output text
          --keyring-dir {{ node_home_dir }}
          --sign-mode direct
        responses:
          "Enter keyring passphrase.*:": "{{ lookup('env', 'KEYRING_PASSWORD') }}\n"
      register: unjail_output
      failed_when: 
        - unjail_output.rc != 0
        - (unjail_output.stdout | regex_search('"code":\s*(\d+)', '\\1') | int) != 0

  always:
    - name: Show raw unjail output for debugging
      ansible.builtin.debug:
        msg: "{{ unjail_output.stdout }}"

    - name: Display txhash, raw_log and codespace fields
      ansible.builtin.debug:
        msg: |
          TX Hash: {{ (unjail_output.stdout | regex_search('txhash: ([a-zA-Z0-9]+)', '\\1')) | default('N/A', true) }}
          Codespace: {{ (unjail_output.stdout | regex_search('codespace: ([a-zA-Z0-9]+)', '\\1')) | default('N/A', true) }}
          Raw Log: {{ (unjail_output.stdout | regex_search('raw_log: ([a-zA-Z0-9]+)', '\\1')) | default('N/A', true) }}
