---
- name: Create the agoric-repo folder
  ansible.builtin.file:
    path: "{{ node_home_dir }}/.agoric-repo"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Clone the repository
  ansible.builtin.git:
    repo: "{{ vars[project][type].source_url }}"
    dest: "{{ node_home_dir }}/.agoric-repo"
    version: "{{ vars[project][type].version }}"
    force: true
  notify:
    - Restart service

- name: Build agoric binary
  ansible.builtin.shell: |
    source {{ nvm.path }}/nvm.sh
    nvm use {{ vars[project][type].node.version }}
    corepack enable
    corepack prepare yarn@4.9.1 --activate
    bin/agd build
  args:
    chdir: "{{ node_home_dir }}/.agoric-repo"
    executable: /bin/bash
  environment:
    PATH: "{{ nvm.path }}/versions/node/{{ vars[project][type].node.version }}/bin:{{ go.root }}/bin:{{ ansible_env.PATH }}"
    NODE_PATH: "{{ nvm.path }}/versions/node/{{ vars[project][type].node.version }}/lib/node_modules"
    GOROOT: "{{ go.root }}"
    GOPATH: "{{ go.path }}"
    GO111MODULE: "{{ go.module111 }}"
  changed_when: false

- name: Create a symbolic link to agroic binary
  ansible.builtin.file:
    src: "{{ node_home_dir }}/.agoric-repo/bin/{{ node_service_default_binary_name[project] }}"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    state: link

- name: Copy general environment file
  ansible.builtin.template:
    src: "{{ env }}/{{ project }}/general.env.j2"
    dest: "{{ node_environment_general_file_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart service
