---
- name: Fetch the axelar service binary
  vars:
    suffix_url: >-
      {{ node_service_default_binary_name[project] }}-{{ ansible_system | lower }}-{{ system_architecture }}-{{ axelar[type].version }}
  ansible.builtin.get_url:
    url: "{{ axelar[type].source_url }}/{{ axelar[type].version }}/{{ suffix_url }}-static"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service
  when: not (fetch_secret_binaries | default(false) | bool)

- name: Fetch the axelar service secret binary
  vars:
    suffix_url: >-
      {{ node_service_default_binary_name[project] }}-{{ ansible_system | lower }}-{{ system_architecture }}-{{ axelar[type].version }}
  ansible.builtin.get_url:
    url: "{{ vault.external.axelar.private_source_url }}/{{ axelar[type].version }}/{{ suffix_url }}-static"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service
  when: fetch_secret_binaries | default(false) | bool
