---
- name: Handle Install binary task
  block:
    - name: Include project-specific install binary task
      ansible.builtin.include_tasks: "{{ project }}.yml"
  rescue:
    - name: Include default install binary task
      ansible.builtin.include_tasks: default.yml
