---
- name: Download pell binary
  ansible.builtin.get_url:
    url: "{{ vars[project][type].source_url }}/{{ vars[project][type].version }}/{{ vars[project][type].suffix_url }}"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    owner: root
    group: root
    mode: "0755"
  notify:
    - Restart service
