---
# Maintains file names, binary names, and anything that is not a directory or path

sommelier_orchestrator_environment_secrets_file_name: "{{ service_identifier }}.secrets.env"
sommelier_orchestrator_config_file_name: config.toml

# binary names
sommelier_orchestrator_service_default_binary_name: gbt

# Cert names
sommelier_orchestrator_server_cert_file_name: server.crt
sommelier_orchestrator_server_key_pkcs8_file_name: server_key_pkcs8.pem

# Key names
sommelier_orchestrator_orchestrator_key_file_name: orchestrator.pem
sommelier_orchestrator_signer_key_file_name: signer.pem
