---
# Maintains file names, binary names, and anything that is not a directory or path

sommelier_orchestrator_config_file_name: config.toml

# binary names
sommelier_orchestrator_service_default_binary_name: steward

# Key names
sommelier_orchestrator_orchestrator_key_file_name: orchestrator.pem
sommelier_orchestrator_signer_key_file_name: signer.pem
