---
- name: Fetch the service secret binary
  vars:
    suffix_url: >-
      {{ vald_default_binary_name }}-{{ ansible_system | lower }}-{{ system_architecture }}-{{ axelar.vald.version }}
  ansible.builtin.get_url:
    url: "{{ vault.external.axelar.private_source_url }}/{{ axelar.vald.version }}/{{ suffix_url }}-static"
    dest: "{{ vald_bin_dir }}/{{ service_identifier }}"
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service
  when: fetch_secret_binaries | default(false) | bool
