---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ vald_home_dir }}"
    directories: "{{ vald_directories }}"
    lib_dir: "{{ vald_lib_dir }}"
    log_file_path: "{{ vald_log_file_path }}"

- name: Fetch the service binary
  vars:
    suffix_url: >
      {{ axelar.vald.version }}/{{ vald_default_binary_name }}-{{ ansible_system | lower }}-{{ system_architecture }}-{{ axelar.vald.version }}
  ansible.builtin.get_url:
    url: "{{ axelar.vald.source_url }}/{{ suffix_url }}"
    dest: "{{ vald_bin_dir }}/{{ service_identifier }}"
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service

- name: Include wasmvm task
  ansible.builtin.include_tasks: configure_wasmvm.yml

- name: Fetch secrets environment file from HCP Vault and save to file
  ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
  vars:
    vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ vald_environment_secrets_file_name }}"
    secret_destination_path: "{{ vald_environment_secrets_file_path }}"
    secret_type: environment

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
