---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ orchestrator_metrics_home_dir }}"
    directories: "{{ orchestrator_metrics_directories }}"
    log_file_path: "{{ orchestrator_metrics_log_file_path }}"

- name: Copy orchestrator metrics script
  ansible.builtin.template:
    src: "orchestrator_metrics.sh.j2"
    dest: "{{ orchestrator_metrics_script_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0755"

- name: Copy orchestrator metrics systemd service file
  ansible.builtin.template:
    src: orchestrator_metrics.service.j2
    dest: "/etc/systemd/system/{{ service_identifier }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service

- name: Copy orchestrator metrics timer service file
  ansible.builtin.template:
    src: orchestrator_metrics.timer.j2
    dest: "/etc/systemd/system/{{ service_identifier }}.timer"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart timer
