---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ node_home_dir }}"
    directories: "{{ node_directories }}"
    log_file_path: "{{ node_log_file_path }}"

- name: Include handle coordinated update
  ansible.builtin.include_tasks: coordinated_update.yml

- name: Include build binary task
  ansible.builtin.include_tasks: build_binary.yml

- name: Get genesis and configuration files
  block:
    - name: Copy configuration file
      ansible.builtin.template:
        src: "{{ env }}/{{ project }}/config.toml.j2"
        dest: "{{ node_config_file_path }}"
        owner: "{{ service_identifier }}"
        group: "{{ service_identifier }}"
        mode: "0644"
      notify:
        - Restart service

    - name: Copy application file
      ansible.builtin.template:
        src: "{{ env }}/{{ project }}/app.toml.j2"
        dest: "{{ node_app_file_path }}"
        owner: "{{ service_identifier }}"
        group: "{{ service_identifier }}"
        mode: "0644"
      notify:
        - Restart service

    - name: Copy genesis file
      ansible.builtin.copy:
        src: "{{ env }}/{{ project }}/genesis.json"
        dest: "{{ node_genesis_file_path }}"
        owner: "{{ service_identifier }}"
        group: "{{ service_identifier }}"
        mode: "0644"
      notify:
        - Restart service

- name: Fetch secrets from HCP Vault and save to files
  when: type == 'validator'
  block:
    - name: Fetch priv validator key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_priv_validator_key_file_name }}"
        secret_destination_path: "{{ node_priv_validator_key_path }}"
        secret_type: key

    - name: Fetch node key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_node_key_file_name }}"
        secret_destination_path: "{{ node_node_key_path }}"
        secret_type: key

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ env }}/{{ project }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
