---
- name: Stop service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: stopped

- name: Backup validator state file
  block:
    - name: Backup validator state file
      ansible.builtin.copy:
        src: "{{ sync_priv_validator_state_file_path }}"
        dest: "{{ sync_home_dir }}"
        remote_src: true
        owner: "{{ service_identifier }}"
        group: "{{ service_identifier }}"
        mode: "0644"
  rescue:
    - name: Handle missing file
      ansible.builtin.debug:
        msg: Source file does not exist

- name: Delete data folder
  ansible.builtin.file:
    path: "{{ sync_data_dir }}"
    state: absent

- name: Delete wasm folder
  ansible.builtin.file:
    path: "{{ sync_home_dir }}/wasm"
    state: absent

- name: Include Snapshot Sync task
  ansible.builtin.include_tasks: snapshot_sync.yml
  when: sync_method == "snapshot_sync"

- name: Include State Sync task
  ansible.builtin.include_tasks: state_sync.yml
  when: sync_method == "state_sync"

- name: Handle Restore validator state file
  block:
    - name: Restore validator state file
      ansible.builtin.copy:
        src: "{{ sync_home_dir }}/priv_validator_state.json"
        dest: "{{ sync_data_dir }}"
        remote_src: true
        owner: "{{ service_identifier }}"
        group: "{{ service_identifier }}"
        mode: "0644"

    - name: Remove validator state file after copy
      ansible.builtin.file:
        path: "{{ sync_home_dir }}/{{ sync_priv_validator_state_file_name }}"
        state: absent
  rescue:
    - name: Handle missing file
      ansible.builtin.debug:
        msg: Source file does not exist

- name: Set ownership for data directory
  ansible.builtin.file:
    path: "{{ sync_data_dir }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    recurse: true

- name: Handle wasm logic
  block:
    - name: Set ownership for wasm directory
      ansible.builtin.file:
        path: "{{ sync_home_dir }}/wasm"
        owner: "{{ service_identifier }}"
        group: "{{ service_identifier }}"
        recurse: true
  rescue:
    - name: Handle missing wasm directory
      ansible.builtin.debug:
        msg: wasm direcotry does't present in home directory

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: restarted
