---
- name: Handle Download and extract snapshots
  block:
    - name: Download and Extract snapshot
      ansible.builtin.shell: |
        set -o pipefail
        curl -o - -L {{ snapshot_url | default(vars[project].snapshot_url) }} | lz4 -c -d - | tar -x -C {{ sync_home_dir }}
      async: 10000
      poll: 10
      args:
        executable: /bin/bash
        creates: "{{ sync_data_dir }}"
